# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8446dbeac79ec07d7d9245ab875437ba752aa5ecc4dac7827bf3cc182bee009c29e2f4da48bcbe1c14fda84980783e2a55da8173931d172363175682745169d3

test:
  secret_key_base: b437694d867a5d2a8e9fd9359626da9e398c3dd4513b704e904f3893cdc0502fd63a79ca18eca9c7137fa2f009ecc6d70806f2db4cb7bc82d7cc0b2e57d13043

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
